services:
  network-deploy-service:
    networks:
      - bankService

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
#    Commented due to memory storage...
#    environment:
#      SPRING_RABBITMQ_HOST: "rabbit"

  microservice-configServer-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configServer:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaServer:8070/eureka/
